In [52]:
# ── Heart Failure Clinical Data ───────────────────────────────────────────────
# Source: https://www.kaggle.com/datasets/andrewmvd/heart-failure-clinical-data
# Task:   Predict heart failure mortality risk
# File:   heart_failure_clinical_records_dataset.csv
# ─────────────────────────────────────────────────────────────────────────────

# TODO: import any additional libraries you need
import pandas as pd
import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns

In [53]:
df = pd.read_csv('../data/heart_failure_clinical_records_dataset.csv')

print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nData types:\n", df.dtypes)
df.head()

Shape: (299, 13)

Columns: ['age', 'anaemia', 'creatinine_phosphokinase', 'diabetes', 'ejection_fraction', 'high_blood_pressure', 'platelets', 'serum_creatinine', 'serum_sodium', 'sex', 'smoking', 'time', 'DEATH_EVENT']

Data types:
 age                         float64
anaemia                       int64
creatinine_phosphokinase      int64
diabetes                      int64
ejection_fraction             int64
high_blood_pressure           int64
platelets                   float64
serum_creatinine            float64
serum_sodium                  int64
sex                           int64
smoking                       int64
time                          int64
DEATH_EVENT                   int64
dtype: object

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [54]:
# Quick look — run this before anything else
print("Missing values:")
print(df.isnull().sum())

print("\nTarget distribution (DEATH_EVENT):")
print(df['DEATH_EVENT'].value_counts())
print(f"Mortality rate: {df['DEATH_EVENT'].mean():.1%}")

# Things to think about:
# - Only 299 rows — how does that affect your modeling choices?
# - The 'time' column is follow-up duration. Should you use it as a feature?

Missing values:
age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

Target distribution (DEATH_EVENT):
DEATH_EVENT
0    203
1     96
Name: count, dtype: int64
Mortality rate: 32.1%

In [55]:
# ── EDA ───────────────────────────────────────────────────────────────────────
# TODO: explore the data
# Ideas:
# - Plot distributions of ejection_fraction, serum_creatinine, age
# - Boxplots comparing survivors vs non-survivors across key features
# - Correlation heatmap

# your code here

In [ ]:
# ── Preprocessing ─────────────────────────────────────────────────────────────
# TODO: prepare data for modeling
# Things to consider:
# - No missing values — lucky!
# - Feature scaling (important for some models)
# - Include or exclude 'time'? Why?
# - Small dataset — consider cross-validation over a single train/test split

# your code here

# Validate Columns
req_cols = {'age', 'anaemia', 'creatinine_phosphokinase', 'diabetes', 'ejection_fraction', 'high_blood_pressure', 'platelets', 'serum_creatinine', 'serum_sodium', 'sex', 'smoking', 'time', 'DEATH_EVENT'}
if not req_cols.issubset(df.columns):
    raise

# Handle null values (just in case)
df.fillna(0, inplace=True)

Missing values:
age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
serum_sodium                0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1,1,270,0
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0,0,271,0
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0,0,278,0
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1,1,280,0
298,50.0,0,196,0,45,0,395000.00,1.6,136,1,1,285,0

In [57]:
# ── Model ─────────────────────────────────────────────────────────────────────
# TODO: build and train your model

# your code here

In [58]:
# ── Evaluation ────────────────────────────────────────────────────────────────
# TODO: evaluate your model
# Suggested metrics:
# - ROC-AUC
# - Precision, Recall, F1
# - Confusion matrix

# Bonus: try building a model using ONLY serum_creatinine + ejection_fraction
# The reference paper found these two features alone predict survival well

# Discussion:
# - How does your AUC compare to random guessing (0.5)?
# - What are the risks of drawing conclusions from only 299 patients?

# your code here